  
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 2
  database: sinatra
  username: postgres
  password: MyPassword
  host: localhost
  port: 5432

development:
  <<: *default
  database: sinatra
  
production:
  <<: *default
  database: sinatra